Check
ProdavecBurrito/OOPFirst pull request #9
Opened 2020-02-19 20:58 UTC by ProdavecBurrito

2020-02-25 21:13 UTC, jawello commented
Все бинарные, временные файлы добавь в игнор!

2020-02-25 21:17 UTC, jawello requested changes
В целом лучше. Комменты в коде по сути к операторам. Есть вопросы по архитектуре, но и объяснить будет сложно, да и ты не поймешь пока. Так что пока забьем. Ответь на вопросы или внеси исправления.

2020-02-25 21:17 UTC, jawello commented on Character.cs
> +        public string name { get; private set; }
Зачем публичному полю свойство? Да и вообще зачем оно тут в принципе (относится и к остальным случаям)

2020-02-25 21:17 UTC, jawello commented on Character.cs
> +        public string writeName;
Почему все поля стали public?

2020-02-25 21:17 UTC, jawello commented on Mines.cs
> +                Thread.Sleep(1);
Это еще зачем?!О_о чтобы рандом разный был?

2020-02-25 21:17 UTC, jawello commented on Mines.cs
> +                Mines m = new Mines(x, y);
На сколько я могу судить, чисто в теории мины и элексиры могу быть на одной клетке? 
Если персонаж наступит на такую клетку, что произойдет?

2020-02-25 21:17 UTC, jawello commented on Point.cs
> +        public Point ()
Для чего написал пустой конструктор?

2020-02-25 21:17 UTC, jawello commented on Program.cs
> +            HealingElixir healingElixirs = new HealingElixir(4);
почему кол-во хилок хардкодом задано? пусть кол-во будет указано в файле с картой.

2020-02-25 21:17 UTC, jawello commented on Program.cs~RFbffea76.TMP
> +﻿using System;
Это временный файл! Добавь все файлы с расширением *.TMP в игнор

2020-02-25 21:50 UTC, ProdavecBurrito commented on Mines.cs
> +                Thread.Sleep(1);
так точно

2020-02-25 21:52 UTC, ProdavecBurrito commented on Character.cs
> +        public string writeName;
что бы класс Message имел доступ к полям

2020-02-25 21:54 UTC, ProdavecBurrito commented on Character.cs
> +        public string name { get; private set; }
эксперимента ради, не более. смотрел, смогу ли свои свойства написать

2020-02-25 21:56 UTC, ProdavecBurrito commented on Mines.cs
> +                Mines m = new Mines(x, y);
То, что я задуманно - он подберет хилку и наступит на мину. одновременно. - к ХП и + к колл. хилок. Проверенно. Ты же сам писал в задании, что мины и хилки могул быть на одном поле

2020-02-25 21:57 UTC, ProdavecBurrito commented on Point.cs
> +        public Point ()
вот тут косяк. он нужен был, но потом перестал быть таковым. уберу

2020-02-25 21:57 UTC, ProdavecBurrito commented on Program.cs
> +            HealingElixir healingElixirs = new HealingElixir(4);
ну, такого задания не было. оке, попробую

2020-02-25 21:58 UTC, ProdavecBurrito commented on Program.cs~RFbffea76.TMP
> +﻿using System;
оке

2020-02-25 22:04 UTC, jawello commented on Character.cs
> +        public string name { get; private set; }
ну ок, пусть будет. Это твой проект в том числе и для экспериментов. Если бы был продакшен код, то я бы однозначно заставил выпилить)

2020-02-25 22:07 UTC, jawello commented on Character.cs
> +        public string writeName;
ну ... по факту ты нарушаешь инкапсуляцию и зону ответственности класса message и делаешь класс character слишком открытым. Ну да ладно, пока ты все еще не очень понимаешь зачем закрывать и как разделять зоны ответственности между классами (да и еще толком не сталкивался с проблемами, которые грозят при таком подходе). Поэтому оставим как есть.

2020-02-25 22:07 UTC, jawello commented on Mines.cs
> +                Thread.Sleep(1);
а вот это уже плохо. где ты взял подобное решение?

2020-02-25 22:13 UTC, ProdavecBurrito commented on Mines.cs
> +                Thread.Sleep(1);
насколько я помню - в уроке говорилось, что можно задать паузу, ибо прога, если очень быстро считает, подставляет одинаковые значения в рандом. изза этого и были одинаковые значения

2020-02-25 22:17 UTC, jawello commented on Mines.cs
> +                Thread.Sleep(1);
`Random rand = new Random(Guid.NewGuid().GetHashCode());`

Вот пример как инициализировать объект rand так, чтобы не возникало такой проблемы. Почитай на досуге как работают Random:

-  [тут](https://habr.com/ru/post/165459/) - первую часть до вариантов решения проблемы и "Используйте один экземпляр класса Random при множественных вызовах"  
- [тут](http://plssite.ru/csharp/csharp_random_article.html)
- [для общего понимания](https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80_%D0%BF%D1%81%D0%B5%D0%B2%D0%B4%D0%BE%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B9%D0%BD%D1%8B%D1%85_%D1%87%D0%B8%D1%81%D0%B5%D0%BB)

2020-02-25 22:18 UTC, jawello commented on Program.cs
> +            HealingElixir healingElixirs = new HealingElixir(4);
Давай сделаю отдельной задачей

2020-02-26 12:09 UTC, jawello approved these changes
Approve

2020-02-26 12:09 UTC, merged